# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Inspection Pipeline

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
#     - name: Notifying on build via Slack
#       if: success()
#       id: slack
#       env:
#         SLACK_BOT_TOKEN: ${{ secrets.MG_SLACKBOT_TOKEN }}
#       uses: voxmedia/github-action-slack-notify-build@v1
#       with:
#         channel: mg-pulse
#         status: STARTING
#         color: warning
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Running ESLint...
      run: npm run pretest
    - name: Running tests...
      run: npm test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./civerage/lcov_report/
#   - name: Publishing package to npm
#    run: npm publish
#      env: 
#        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
